### ISSUE TITLE
GraphQL::Schema can't define 'enable_preloading'

### ISSUE THREAD

**Issue by egonm12** [ConsultingMD/graphql-preload#16]
`graphql-preload 2.1.0` gives me the following error when defining `enable_preloading`:

`GraphQL::Schema can't define 'enable_preloading'`

My schema looks like this:
```
MyAppSchema = GraphQL::Schema.define do
  use GraphQL::Batch
  enable_preloading

  mutation(Types::MutationType)
  query(Types::QueryType)
end
```

It only works when defining `include GraphQL::Preload::SchemaMethods` in my schema. 

It works fine with version `2.0.1.`.

**Comment by cassiopagnoncelli** [comment]
It's also buggy here

**Comment by thiagofelix** [comment]
I believe it is because the support for old syntax (ObjectType.define) was removed on #11 

**Old api support**
https://github.com/ConsultingMD/graphql-preload/blob/bdf7fc620ac981b52771f1f09fa680ce06be768c/lib/graphql/preload.rb#L5-L17

@CyborgMaster can you confirm that?

I think we should keep both API so people can transition from one to another in small steps as recommended on [graphql-ruby](https://graphql-ruby.org/schema/class_based_api.html#rationale--goals) documentation.

**Comment by raysuelzer** [comment]
So, what would be the new way to enable the preloading?

**Comment by thiagofelix** [comment]
The way of enabling preloading shouldn't change depending on the ruby-graphql syntax you are following. 

The reason why it stoped working is because the `GraphQL::Field.accepts_definitions` calls highlighted above were removed and therefore `enable_preloading` stop working inside a `Schema.define` block.

**Comment by cassiopagnoncelli** [comment]
@thiagofelix So using the new syntax should solve the issue?
