### ISSUE TITLE
rescue_from isn't working due to promises

### ISSUE THREAD

**Issue by ngouy** [ConsultingMD/graphql-preload#17]
Using graphql-ruby 1.8.x, I cannot rescue errors from queries as I do for mutations due to batching and its Promises. How can i Handle that ?

for mutation this is working :
```rb
class MySchema < GraphQL::Schema
    enable_preloading

    mutation Mutations::Root
    query Queries::Root

    rescue_from(Pundit::NotAuthorizedError) {
        raise GraphQL::ExecutionError, "You are forbidden to access this field."
    }
end
```

**Comment by nekogami** [comment]
So I ended end finding a way to make that works here's a code sample of how I do it.

```
class MySchema < GraphQL::Schema
  # [... query mutation subscription and plugin registry]
end


GraphQL::Errors.configure(MySchema) do
  rescue_from ActiveRecord::RecordNotFound do
    GraphQL::ExecutionError.new("Resource not found", extensions: { code: :resource_not_found })
  end
end

MySchema.enable_preloading # weird hotfix to make preload works
MySchema.graphql_definition # weird hotfix to avoid a "duplicate type declaration" error

```
From my understanding it is related to https://github.com/rmosolgo/graphql-ruby/issues/1598

You have to call MySchema.enable_preloading at the end instead of inside the schema definition, also, I didn't try the reorder of rescue_from that they talked about since errors were already outside of the schema in our project.

**Comment by rmosolgo** [comment]
~~Hi, I just merged some new error handling for the interpreter runtime which handles promises appropriately: https://github.com/rmosolgo/graphql-ruby/pull/2458~~

~~Please give it a try! If you run into a problem, please open a new issue.~~

Edit: sorry, I thought this was an open PR on graphql-ruby 😬
